In [1]:
import torch


In [2]:
t1 = torch.tensor(4.)
t1


tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2


tensor([1., 2., 3., 4.])

In [6]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3D array : two matrices in an array
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [8]:
t1.shape



torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t3.shape

torch.Size([3, 2])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [12]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [13]:
# arith operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [14]:
y.backward()


In [15]:
print(('dy/dx : ', x.grad))


('dy/dx : ', None)


In [16]:
print('dy/dw : ', w.grad)

dy/dw :  tensor(3.)


In [18]:
print('dy/db: ', b.grad)


dy/db:  tensor(1.)


In [19]:
import  numpy as np
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [20]:
# convert numpy array to a PyTorch tensor
# doesn't create copy of the data
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [21]:
# creates copy of the data in memory
y = torch.tensor(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [22]:
# torch sensor to numpy array
z = y.numpy()
z


array([[1., 2.],
       [3., 4.]])

In [ ]:
# deep learning run in GPU from nvidia
# pytorch implemented for GPU

